### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by weisong82** [yingtu/openimages_downloader#1]
unexpected fault address 0x0
fatal error: fault
[signal 0xb code=0x80 addr=0x0]

goroutine 366 [running]:

```
    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0

    :0
```

goroutine 1 [chan send]:
main.main
        /root/openimages/downloader.go:79

goroutine 3 [runnable]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 4 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 5 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 6 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 7 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 8 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

▽oroutine 9 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 10 [IO wait]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 11 [runnable]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 12 [runnable]:
main.HTTPDownload
        /root/openimages/downloader.go:128
main.fetcher
        /root/openimages/downloader.go:107
created by main.main
        /root/openimages/downloader.go:45

goroutine 363 [chan receive]:

goroutine 373 [runnable]:
Segmentation fault

**Comment by huichen** [comment]
可能是网络问题，抓取图片需要翻墙

**Comment by weisong82** [comment]
不是，美国节点的机器，wget抓过cvs里面链接ok
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-86-generic x86_64)
